name: Build

on: [push, pull_request]

jobs:
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1

        - name: Build
          run: |
            mkdir build
            cd build
            cmake .. -DSDL_TEST=ON
            cmake --build .

    linux:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v1

        - name: Setup
          run: |
            sudo apt-get update
            sudo apt-get install build-essential git cmake ninja-build pkg-config \
            libasound2-dev libpulse-dev libaudio-dev libjack-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev \
            libxss-dev libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev \
            libegl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev \
            libsndio-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev

        - name: Linux
          run: |
            mkdir build
            cd build
            cmake .. -GNinja -DSDL_TEST=ON
            cmake --build .

    windows:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v1

        - name: Build
          run: |
            mkdir build
            cd build
            cmake .. -DSDL_TEST=ON
            cmake --build .
